name: flutter_map
description: A flutter implementation of Leaflet
version: 0.0.11+1
authors:
- John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/apptreesoftware/flutter_map

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  latlong2:
    git: https://github.com/johnpryan/latlong2.git
  tuple: ^1.0.0
  transparent_image: ^0.1.0
